apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: client    # Name of the kubernetes resource
  labels:
    app: client
spec:
  type: ClusterIP                # Exposes the service by opening a port on each node
  selector:
    app: client     # Any Pod matching the label `app=social-login-app-client` will be picked up by this service
  ports:                        # Forward incoming connections on port 8081 to the target port 80 in the Pod
  - port: 80
    targetPort: 80
  clusterIP: None